### ISSUE TITLE
Trouble with install last version

### ISSUE THREAD

**Issue by EugeneVdovenko** [GotCms/GotCms#286] opened 2015-06-18 14:28 UTC
I downloaded last version through Git and ran it. But, it not working. At the log-file i see below:
PHP message: PHP Fatal error:  Cannot redeclare class Zend\Loader\SplAutoloader in /var/www/projects/gotcms/vendor/Zend/Loader/SplAutoloader.php on line 22

I have on server Nginx 1.2.1 and PHP 5.6.7-1.

**Comment by PierreRambaud** [comment] 2015-06-18 14:56
Hi,

Can you show me more about the stack trace? And have you the capability to test with older PHP version such as 5.5 or 5.4? 

Regards

**Comment by EugeneVdovenko** [comment] 2015-06-19 06:28
Hm..

Nginx-log:
2015/06/19 08:51:55 [error] 20232#0: *20 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot redeclare class Zend\Loader\SplAutoloader in /var/www/projects/gotcms/vendor/Zend/Loader/SplAutoloader.php on line 22" while reading response header from upstream, cllient: 4.4.4.4, server: gotcms.xxx.ru, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.socket:", host: "gotcms.xxx.ru"

And I have blank page in my browser.

If I use OpenServer (WAMP) - all OK. But, it hasn't PHP 5.6, only 5.5.

**Comment by PierreRambaud** [comment] 2015-06-19 07:54
I tried to reproduce on Debian Jessie with:
```
$ php -v
PHP 5.6.9-0+deb8u1 (cli) (built: Jun  5 2015 11:03:27) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans
```
But seems to works fine :/

I think you should have a look directly in php logs instead of nginx logs, there must be more information, such as the stacktrace.

Also, can you do a `composer install` and try to run tests? (scripts/runtests.sh)

Regards

**Comment by EugeneVdovenko** [comment] 2015-06-19 09:08
Hi,

php-fpm log-file is empty :(

If I run tests, I see 
```
/gotcms/scripts$ ./runtests.sh
-d zend.enable_gc=0 --verbose
Can't connect to database exiting.
```
At index.php the line
```
require 'init_autoloader.php';
```
work in normal and returns $configuration
```
Array
(
    [modules] => Array
        (
            [0] => AssetManager
            [1] => GcFrontend
            [2] => GcBackend
            [3] => GcConfig
            [4] => GcContent
            [5] => GcDevelopment
            [6] => GcModule
            [7] => GcStatistics
        )

    [module_listener_options] => Array
        (
            [config_glob_paths] => Array
                (
                    [0] => config/autoload/{,*.}{local,global}.php
                )

            [config_cache_enabled] => 
            [cache_dir] => data/cache
            [module_paths] => Array
                (
                    [0] => ./module
                    [1] => ./vendor
                    [2] => ./extensions/ZfModules
                )

        )

    [service_manager] => Array
        (
            [use_defaults] => 1
            [factories] => Array
                (
                )

        )

    [autoloader] => Array
        (
            [namespaces] => Array
                (
                    [Assetic] => /var/www/projects/gotcms/config/../vendor/Assetic
                    [elFinder] => /var/www/projects/gotcms/config/../vendor/elFinder
                    [Parsedown] => /var/www/projects/gotcms/config/../vendor/Parsedown
                    [Datatypes] => /var/www/projects/gotcms/config/../library/Datatypes
                    [Gc] => /var/www/projects/gotcms/config/../library/Gc
                    [0] => /var/www/projects/gotcms/config/../extensions/Datatypes
                )

            [autoregister_zf] => 1
        )

)
```
Next, Zend\Mvc\Application::init() don;t work. If I insert var_dump after 
```
$application = Zend\Mvc\Application::init($configuration);
```
or into function
```
Zend\Mvc\Application::init()
```
write an error at nginx-log. But, if I write before class_exists and method_exists - its returns TRUE.

**Comment by EugeneVdovenko** [comment] 2015-06-19 09:09
php -v
PHP 5.6.7-1 (cli) (built: Mar 24 2015 12:30:15)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with XCache v3.2.0, Copyright (c) 2005-2014, by mOo
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies
    with XCache Optimizer v3.2.0, Copyright (c) 2005-2014, by mOo
    with XCache Cacher v3.2.0, Copyright (c) 2005-2014, by mOo
    with XCache Coverager v3.2.0, Copyright (c) 2005-2014, by mOo

**Comment by PierreRambaud** [comment] 2015-06-19 09:30
You must apply some changes for testing: https://github.com/GotCms/GotCms/blob/master/CONTRIBUTING.md#running-tests

it's fun, if you have a look in https://github.com/GotCms/GotCms/blob/master/vendor/Zend/Loader/SplAutoloader.php there a return at the beginning of the file if interface already exists --'

**Comment by PierreRambaud** [comment] 2015-06-19 09:50
I just retry by using XCache and nothing happened :/

```
PHP 5.6.9-0+deb8u1 (cli) (built: Jun  5 2015 11:03:27) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with XCache v3.2.0, Copyright (c) 2005-2014, by mOo
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans
    with XCache Optimizer v3.2.0, Copyright (c) 2005-2014, by mOo
    with XCache Cacher v3.2.0, Copyright (c) 2005-2014, by mOo
    with XCache Coverager v3.2.0, Copyright (c) 2005-2014, by mOo
```

**Comment by EugeneVdovenko** [comment] 2015-06-19 10:54
Ok, I see it later.

I downloaded older version and tried it to run
v.1.5.0 is working. 
v.1.5.1 does not working

**Comment by PierreRambaud** [comment] 2015-06-19 12:09
So, seems to be a bug with Zend Framework 2.3.3 :/

**Comment by EugeneVdovenko** [comment] 2015-06-19 13:00
Doesn't work in line
```
if (interface_exists('Zend\Loader\SplAutoloader')) {
    return;
}
```
in SplAutoloader.php.

If I rename, for example, to "interface SplAutoloader_1" - all works again.
Its strange... :(

**Comment by EugeneVdovenko** [comment] 2015-06-19 14:02
I write below:
```
if (interface_exists('Zend\Loader\SplAutoloader')) {
    return;
} else {
    interface SplAutoloader
    {
        ... interface's body ...
    }
}
```
but I think this a badly idea, and I can't update ZF2 in future. :(

**Comment by PierreRambaud** [comment] 2015-06-19 14:57
I already check and it's define once in all the project or in my computer :/
Editing this code is bad, you will unable to update due to conflicts and have again the bug if use latest zf2 release.
I encourage you to open a issue on https://github.com/zendframework/zf2/issues you may be able to help you more than I can :/ When you will create this issue, tell me please, I need to know wtf happened :/

**Comment by EugeneVdovenko** [comment] 2015-06-22 14:38
I restarted php-fpm and it work.
I think the problem with the PHP-cache (OPcache or xcache or both).
I am trying  understand...

**Comment by PierreRambaud** [comment] 2015-06-22 15:08
Strange :/

**Comment by PierreRambaud** [comment] 2015-06-25 07:27
I close this issue, reopen if happened again.

**Closed by PierreRambaud** 2015-06-25 07:27 UTC
Labels: bug
